### PR TITLE
Backlinks getters throws for unmanaged objects

### LINKED ISSUE #1106: Error occurs when a backlink iterable is empty
### What happened?

For example:

```
@Backlink(#items)
late Iterable<$ExampleList> exampleLists;
```

When an item has no relationship with `ExampleList`, it seems not possible to access `exampleLists`.

`print(item.exampleLists.isEmpty);
`

results in:

```
Exception has occurred.
_CastError (type 'Null' is not a subtype of type 'RealmResults<ExampleList>' in type cast)
```

### Repro steps

See above

### Version

2.19.0-444.3.beta / 3.7.0-1.3.pre

### What Atlas Services are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

0.9.0+rc

### Code snippets

_No response_

### Stacktrace of the exception/crash you're getting

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by desistefanova**
Using backlinks is only possible for managed(persisted) objects.
Fixes #1106
Fix test: "Realm.open (flexibleSync) - listen for download progress on an empty realm"

### CODE REVIEW

**Review by nielsenko — CHANGES_REQUESTED** [review]
We should not change the output of the generator for this in my opinion. This should be handled in the accessor.

**Comment by desistefanova** [comment]
> We should not change the output of the generator for this in my opinion. This should be handled in the accessor.

How could we know in the accessor that this is a backlink?

File: generator/lib/src/realm_field_info.dart [hunk 1]
```diff
@@ -80,7 +80,12 @@ class RealmFieldInfo {
   Iterable<String> toCode() sync* {
     final getTypeName = type.isRealmCollection ? basicMappedTypeName : basicNonNullableMappedTypeName;
     yield '@override';
-    yield "$mappedTypeName get $name => RealmObjectBase.get<$getTypeName>(this, '$realmName') as $mappedTypeName;";
+    if (isRealmBacklink) {
+      final backlinkGetter = "RealmObjectBase.get<$getTypeName>(this, '$realmName')";
+      yield "$mappedTypeName get $name => ($backlinkGetter as $mappedTypeName?)?? $mappedTypeName();";
+    } else {
+      yield "$mappedTypeName get $name => RealmObjectBase.get<$getTypeName>(this, '$realmName') as $mappedTypeName;";
```
Comment (nielsenko) [inline generator/lib/src/realm_field_info.dart:87]:
```suggestion
      yield "$mappedTypeName get $name => $backlinkGetter as $mappedTypeName;";
```

**Review by nielsenko — APPROVED** [review]
You are right about not being able to do this in the accessor with the current design.

**Review by blagoev — CHANGES_REQUESTED** [review]
.NET throws an exception. Why are we diverging on this?

**Comment by desistefanova** [comment]
> #1106

We have an user request with a reasonable argument: https://github.com/realm/realm-dart/issues/1106#issuecomment-1387179707

**Comment by desistefanova** [comment]
> .NET throws an exception. Why are we diverging on this?

We have an user request with a reasonable argument: https://github.com/realm/realm-dart/issues/1106#issuecomment-1387179707

**Review by nielsenko — CHANGES_REQUESTED** [review]
Missing the changes to `RealmGenerator`

**Review by nielsenko — APPROVED** [review]

File: generator/lib/src/realm_field_info.dart [hunk 2]
```diff
@@ -80,7 +80,8 @@ class RealmFieldInfo {
   Iterable<String> toCode() sync* {
     final getTypeName = type.isRealmCollection ? basicMappedTypeName : basicNonNullableMappedTypeName;
     yield '@override';
-    yield "$mappedTypeName get $name => RealmObjectBase.get<$getTypeName>(this, '$realmName') as $mappedTypeName;";
+    final validateBacklink = isRealmBacklink ? ", validateBacklink: true" : "";
+    yield "$mappedTypeName get $name => RealmObjectBase.get<$getTypeName>(this, '$realmName'$validateBacklink) as $mappedTypeName;";
```
Comment (blagoev) [inline generator/lib/src/realm_field_info.dart:84]: This could check if the object isManaged and throw here.

File: test/realm_test.dart [hunk 3]
```diff
@@ -1345,11 +1345,14 @@ Future<void> main([List<String>? args]) async {
...
-
+    final completer = Completer<void>();
     var syncedRealm = await getRealmAsync(configuration, onProgressCallback: (syncProgress) {
       transferredBytes = syncProgress.transferredBytes;
+      if (syncProgress.transferredBytes == syncProgress.transferableBytes) {
+        completer.complete();
+      }
     });
-
+    completer.future.timeout(Duration(milliseconds: 300), onTimeout: () => throw Exception("onProgressCallback does not happen."));
```
Comment (blagoev) [inline test/realm_test.dart:1355]:
```suggestion
    completer.future.timeout(Duration(milliseconds: 300), onTimeout: () => throw Exception("onProgressCallback did not happen."));
```

**Review by blagoev — CHANGES_REQUESTED** [review]

File: generator/lib/src/realm_field_info.dart (hunk 2 above)
Comment (desistefanova) [reply generator/lib/src/realm_field_info.dart:84]: The purpose was the check and the exception to be in one place. Otherwise this will be repeated for all the backlink properties:
```dart
RealmResults<Source> get oneToMany {
    if (!isManaged) {
      throw RealmException("Using backlinks is only possible for managed(persisted) objects.");
    }
    return RealmObjectBase.get<Source>(this, 'oneToMany') as RealmResults<Source>;
  }
```

File: lib/src/realm_object.dart [hunk 4]
```diff
@@ -313,7 +313,10 @@ mixin RealmObjectBase on RealmEntity implements RealmObjectBaseMarker, Finalizab
   };
 
   /// @nodoc
-  static Object? get<T extends Object?>(RealmObjectBase object, String name) {
+  static Object? get<T extends Object?>(RealmObjectBase object, String name, {bool validateBacklink = false}) {
```
[the remark this answers is not in the document]
Comment (desistefanova) [reply lib/src/realm_object.dart:316]: I agree, that it is not good we to change the interface, that's why it was added as a discussion point. 
An optional parameter wouldn't be a problem, but still this parameter is too specific for such a general method.
Unfortunately, we don't have any information about `RealmPropertyType` and this is the reason I have added this parameter.

File: generator/lib/src/realm_field_info.dart (hunk 2 above)
Comment (blagoev) [reply generator/lib/src/realm_field_info.dart:84]: why would be a problem to be repeated? This is generated code.

File: lib/src/realm_object.dart (hunk 4 above)
[the remark this answers is not in the document]
Comment (blagoev) [reply lib/src/realm_object.dart:316]: it is not easy to generalize it and if we do it it will negatively impact the benefit of doing it. Hence I suggested to check in-place in the generated code

[the remark this answers is not in the document]
Comment (desistefanova) [reply lib/src/realm_object.dart]: Ok. This is done.

File: generator/lib/src/realm_field_info.dart (hunk 2 above)
Comment (desistefanova) [reply generator/lib/src/realm_field_info.dart]: Ok, Done.

File: generator/lib/src/realm_field_info.dart [hunk 5]
```diff
@@ -80,8 +80,13 @@ class RealmFieldInfo {
   Iterable<String> toCode() sync* {
     final getTypeName = type.isRealmCollection ? basicMappedTypeName : basicNonNullableMappedTypeName;
     yield '@override';
-    final validateBacklink = isRealmBacklink ? ", validateBacklink: true" : "";
-    yield "$mappedTypeName get $name => RealmObjectBase.get<$getTypeName>(this, '$realmName'$validateBacklink) as $mappedTypeName;";
+    if (isRealmBacklink) {
+      yield "$mappedTypeName get $name {";
+      yield "if(!isManaged){throw RealmException('Using backlinks is only possible for managed(persisted) objects.');}";
```
Comment (blagoev) [inline generator/lib/src/realm_field_info.dart:85]: I would suggest formatting this a bit here. The generator code should be readable by us

File: CHANGELOG.md [hunk 6]
```diff
@@ -4,7 +4,7 @@
 * None
 
 ### Fixed
-* None
+* Getting `Backlink` properties of not persisted objects will throw exception: "Using backlinks is only possible for managed(persisted) objects." ([#1293](https://github.com/realm/realm-dart/pull/1293)).
```
Comment (blagoev) [inline CHANGELOG.md:7]:
```suggestion
* Getting `Backlink` properties of unmanaged Realm objects will throw exception: "Using backlinks is only possible for managed objects." ([#1293](https://github.com/realm/realm-dart/pull/1293)).
```

File: generator/lib/src/realm_field_info.dart (hunk 5 above)
Comment (blagoev) [reply generator/lib/src/realm_field_info.dart:85]: no need to use persisted when we say managed and this is the word we are using across the docs and api docs imo
```suggestion
      yield "if(!isManaged){throw RealmException('Using backlinks is only possible for managed objects.');}";
```

File: generator/lib/src/realm_field_info.dart [hunk 7]
```diff
@@ -80,7 +80,13 @@ class RealmFieldInfo {
   Iterable<String> toCode() sync* {
     final getTypeName = type.isRealmCollection ? basicMappedTypeName : basicNonNullableMappedTypeName;
     yield '@override';
-    yield "$mappedTypeName get $name => RealmObjectBase.get<$getTypeName>(this, '$realmName') as $mappedTypeName;";
+    if (isRealmBacklink) {
+      yield "$mappedTypeName get $name {";
+      yield "if(!isManaged){throw RealmException('Using backlinks is only possible for managed(persisted) objects.');}";
```
Comment (blagoev) [inline generator/lib/src/realm_field_info.dart:85]: Should this be a `RealmError`. I think we are pretty incosistent with these validations but the question here is still valid I think?

**Review by blagoev — CHANGES_REQUESTED** [review]

**Review by blagoev — APPROVED** [review]

**Review by nielsenko — APPROVED** [review]
Okay
