### PR TITLE
SyncErrorCategory.resolve

### LINKED ISSUE #676: syncErrorHandler - provide better details in SyncError
I'm using the `flutter_flexible_sync` example as the basis of a POC I'm working on, and after adding sync capabilities with Atlas, I'm not able to make the app work in offline mode.

Am I doing something wrong?

This is the code I'm using to create the `Realm` object.
``` dart
Future<Realm> createRealm(String appId) async {
  final user = await App(AppConfiguration(appId)).logIn(
    Credentials.anonymous(),
  );

  final realm = Realm(
    Configuration.flexibleSync(
      user,
      [
        // ...
      ],
    ),
  );
  print("Created local realm db at: ${realm.config.path}");

  realm.subscriptions.update((mutableSubscriptions) {
    mutableSubscriptions.add(realm.all<Car>());
    mutableSubscriptions.add(realm.all<Person>());
  });
  await realm.subscriptions.waitForSynchronization();
  print("Syncronization completed for realm: ${realm.config.path}");

  return realm;
}
```

And this is the issue generated when trying to launch the app in offline mode:

```
flutter: [INFO] Realm: Connection[1]: Session[1]: client_reset_config = false, Realm exists = true, client reset = false
flutter: [ERROR] Realm: Failed to resolve 'ws.realm.mongodb.com:443': Host not found (authoritative)
```

### PR DESCRIPTION
**Pull request by desistefanova**
Add `SyncErrorCategory.resolve`, `SyncResolveError` and `SyncResolveErrorCode` for network resolution errors when sync. 
The error is handled at syncErrorHandler in FlexibleSyncConfiguration.
Related to #676 

- Todo: add more tests after https://github.com/realm/realm-core/issues/6015 is fixed.

### CODE REVIEW

File: lib/src/configuration.dart [hunk 1]
```diff
@@ -645,6 +645,8 @@ class SyncError extends RealmError {
         return SyncConnectionError(message, category, SyncConnectionErrorCode.fromInt(code), isFatal: isFatal);
       case SyncErrorCategory.session:
         return SyncSessionError(message, category, SyncSessionErrorCode.fromInt(code), isFatal: isFatal);
+      case SyncErrorCategory.resolve:
+        return SyncResolveError(message, category, SyncResolveErrorCode.values[code]);
```
Comment (nielsenko) [inline lib/src/configuration.dart:649]: Why not `.fromInt` here`?

**Review by nielsenko — APPROVED** [review]

File: test/session_test.dart [hunk 2]
```diff
@@ -363,6 +363,25 @@ Future<void> main([List<String>? args]) async {
...
+        final sessionError = syncError.as<SyncResolveError>();
+        expect(sessionError.category, SyncErrorCategory.resolve);
+        expect(sessionError.code, SyncResolveErrorCode.noData);
+        expect(sessionError.message, "Simulated session error");
+        expect(syncError.codeValue, SyncResolveErrorCode.noData.index);
+      },
+    );
+    final realm = getRealm(config);
+    realm.syncSession.raiseError(SyncErrorCategory.resolve, SyncResolveErrorCode.noData.index, false);
+  }, skip: "waiting issue: https://github.com/realm/realm-core/issues/6015 to be fixed");
```
Comment (blagoev) [inline test/session_test.dart:384]: Lets add a todo comment here

**Review by blagoev — APPROVED** [review]

File: lib/src/configuration.dart (hunk 1 above)
Comment (desistefanova) [reply lib/src/configuration.dart:649]: Because the codes are still not released.
