### PR TITLE
Reorder AuthProviderType values

### LINKED ISSUE #992: [Bug]: Wrong user.provider type for facebook, google and apple
### What happened?

When login with google credentials it returns user.provider = AuthProviderType.facebook.

### Repro steps

 ```dart
  final app = App(configuration);
  final tokenId ="some valid google token id";
  final credentials = Credentials.googleIdToken(tokenId);
  final user = await app.logIn(credentials);
  expect(user.provider, AuthProviderType.google);// actually it was facebook
```

### Version

0.5.0+beta and 0.6.0+beta

### What Realm SDK flavor are you using?

MongoDB Atlas (i.e. Sync, auth, functions)

### What type of application is this?

Dart standalone application

### Client OS and version

Windows 11

### Code snippets

 ```dart
  final app = App(configuration);
  final tokenId ="some valid google token id";
  final credentials = Credentials.googleIdToken(tokenId);
  final user = await app.logIn(credentials);
  expect(user.provider, AuthProviderType.google);// actually it was facebook
```

### Stacktrace of the exception/crash you're getting

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by desistefanova**
- Returned `user.provider` was wrong for facebook, google and apple. All the other providers were correct, because their numbers remains the same.

- When we login with `Credentials.anonymous(reuseCredentials: false)` the returned user.provider is also `AuthProviderType.anonymous` instead of `anonymousNoReuse`. To be discussed.

Fixes  #992

### CODE REVIEW

**Review by nirinchev — CHANGES_REQUESTED** [review]
This looks fine, but let's add tests to make sure it doesn't regress. You can use `realm_auth_credentials_get_provider` to make sure the provider is the same. I'm thinking of tests like:

```dart
final credentials = Credentials.anonymous();
expect(credentials.readProviderFromCore(), AuthProviderType.anonymous);
expect(credentials.provider, AuthProviderType.anonymous);
```

where `readProviderFromCore` is an internal function that calls `realm_auth_credentials_get_provider`.

File: test/credentials_test.dart [hunk 1]
```diff
@@ -38,6 +39,8 @@ Future<void> main([List<String>? args]) async {
 
     expect(user1, user2);
     expect(user1, isNot(user3));
+    expect(user1.provider, AuthProviderType.anonymous);
+    expect(user3.provider, AuthProviderType.anonymous);
```
Comment (desistefanova) [inline test/credentials_test.dart:43]: After login with with anonymous `reuseCredentials: false`  we receive `AuthProviderType.anonymous` instead of `AuthProviderType.anonymousNoReuse`. It is because for the server both credentials are "anon-user" and this is the way they are mapped in `provider_type_from_enum`. @nirinchev do you think we have to create an issue about that?

Comment (nirinchev) [reply test/credentials_test.dart:43]: No, apparently that's intentional. We should probably remove the noreuse provider type. As that's not something users should ever deal with.

File: lib/src/credentials.dart [hunk 2]
```diff
@@ -139,6 +139,8 @@ extension CredentialsInternal on Credentials {
   }
 
   RealmAppCredentialsHandle get handle => _handle;
+
+  AuthProviderType readProviderFromCore() => realmCore.userGetCredentialsProviderType(this);
```
Comment (blagoev) [inline lib/src/credentials.dart:143]:
```suggestion
  /// This should be only used for testing
  AuthProviderType get credentialsProviderType => realmCore.userGetCredentialsProviderType(this);
```
we have similar comment elsewhere and also suggested a change to a getter and the rename

**Review by blagoev — APPROVED** [review]
Its ok, I added small suggestion

File: test/credentials_test.dart (hunk 1 above)
Comment (desistefanova) [reply test/credentials_test.dart:43]: Maybe we have to think about it, because when we pass the credentials to core they expect `anonymousNoReuse` to know whether to reuse the users or not.

Comment (nirinchev) [reply test/credentials_test.dart:43]: Right, but we construct the credentials by calling `realmCore.createAppCredentialsAnonymous` - we don't provide the actual enum value to anyone. We store it as a field on the dart credentials, but I don't believe that's actually ever used anywhere and we might as well turn that into a property that reads the value from Core.

**Comment by blagoev** [comment]
@desistefanova why not changelog. Isn't this a fix or this was a fix on a version we have not released yet?

File: test/credentials_test.dart (hunk 1 above)
Comment (desistefanova) [reply test/credentials_test.dart:43]: OK, I made anonymousNoReuse hidden.

**Comment by desistefanova** [comment]
> @desistefanova why not changelog. Isn't this a fix or this was a fix on a version we have not released yet?

Yes I will add a row. It is a fix for a released version.

File: lib/src/credentials.dart [hunk 3]
```diff
@@ -61,9 +62,13 @@ enum AuthProviderType {
...
-        return type;
+    if (value == AuthProviderType._anonymousNoReuse._value) {
+      return AuthProviderType.anonymous;
+    } else {
+      for (final type in AuthProviderType.values) {
+        if (type._value == value) {
+          return type;
+        }
       }
     }
```
Comment (nirinchev) [inline lib/src/credentials.dart:73]:
```suggestion
    if (value == AuthProviderType._anonymousNoReuse._value) {
      return AuthProviderType.anonymous;
    }
    
    return AuthProviderType.values.firstWhere((v) => v._value == value);
```

And we can remove the argument exception at the end.

**Review by nirinchev — APPROVED** [review]
