### PR TITLE
results - requested wrong index

### LINKED ISSUE #285: Add a test for results wrong index error

### PR DESCRIPTION
**Pull request by desistefanova**
New test added for getting element from results by not existing index. Fixes #285 
Fails for Mac OS. Tests [issue](https://github.com/realm/realm-core/issues/5233).

### CODE REVIEW

File: test/results_test.dart [hunk 1]
```diff
@@ -138,6 +138,21 @@ Future<void> main([List<String>? args]) async {
...
+    var config = Configuration([Car.schema]);
+    var realm = Realm(config);
+
+    final car = Car('');
+    realm.write(() => realm.add(car));
+
+    final cars = realm.all<Car>();
+    realm.write(() => realm.deleteMany(cars));
+
+    expect(() => cars[0], throws<RealmException>("Requested index 0 in empty Results"));
```
Comment (blagoev) [inline test/results_test.dart:151]: Why not just test this after opening the Realm since its empty we could skip adding objects to the realm

**Review by blagoev — CHANGES_REQUESTED** [review]

File: test/results_test.dart (hunk 1 above)
Comment (desistefanova) [reply test/results_test.dart:151]: Done

**Review by blagoev — APPROVED** [review]
