### PR TITLE
SyncSessionErrorCode.compensatingWrite(231)

### LINKED ISSUE #676: syncErrorHandler - provide better details in SyncError
I'm using the `flutter_flexible_sync` example as the basis of a POC I'm working on, and after adding sync capabilities with Atlas, I'm not able to make the app work in offline mode.

Am I doing something wrong?

This is the code I'm using to create the `Realm` object.
``` dart
Future<Realm> createRealm(String appId) async {
  final user = await App(AppConfiguration(appId)).logIn(
    Credentials.anonymous(),
  );

  final realm = Realm(
    Configuration.flexibleSync(
      user,
      [
        // ...
      ],
    ),
  );
  print("Created local realm db at: ${realm.config.path}");

  realm.subscriptions.update((mutableSubscriptions) {
    mutableSubscriptions.add(realm.all<Car>());
    mutableSubscriptions.add(realm.all<Person>());
  });
  await realm.subscriptions.waitForSynchronization();
  print("Syncronization completed for realm: ${realm.config.path}");

  return realm;
}
```

And this is the issue generated when trying to launch the app in offline mode:

```
flutter: [INFO] Realm: Connection[1]: Session[1]: client_reset_config = false, Realm exists = true, client reset = false
flutter: [ERROR] Realm: Failed to resolve 'ws.realm.mongodb.com:443': Host not found (authoritative)
```

### LINKED ISSUE #1024: [Bug]: syncErrorHandler doesn't occur because of mapping error codes exception
### What happened?

Missing value 231 in `SyncSessionErrorCode` enum.
An error happen while mapping the error codes  `RealmError("Unknown SyncSessionErrorCode")`.
Then syncErrorHandler doesn't occur for the end user.
An error is printed as INFO:
`flutter: [INFO] Realm: Connection[1]: Session[1]: Received: ERROR "Client attempted a write that is outside of permissions or query filters; it has been reverted" (error_code=231, try_again=true, error_action=Warning)`

### Repro steps

Open a synced Realm and add subscription with query filtering all the dogs with breed "puddel". Then add a new dog with breed "bulldog". See the code snippet.

### Version

0.7.0+rc

### What Realm SDK flavor are you using?

MongoDB Atlas (i.e. Sync, auth, functions)

### What type of application is this?

Flutter Application

### Client OS and version

Windows 11

### Code snippets

```dart
  App app = App(AppConfiguration(".........."));
  final user = await app.logIn(Credentials.anonymous());
  final config = Configuration.flexibleSync(
    user,
    [Dog.schema],
    syncErrorHandler: (p0) {
      print(p0);
    },
  );
  realm = Realm(config);

  final RealmResults<Dog> query = realm.query<Dog>(r'breed LIKE[c] $0', ['puddel']);
  if (realm.subscriptions.find(query) == null) {
    realm.subscriptions.update((mutableSubscriptions) {
      mutableSubscriptions.add(query);
    });

    realm.subscriptions.waitForSynchronization();
  }

  realm.write(() {
     realm.add(Dog(ObjectId(), name: "Foxi", breed: "bulldog"));
  });
```

### Stacktrace of the exception/crash you're getting

```shell
static SyncSessionErrorCode fromInt(int code) {
    final mappedCode = SyncSessionErrorCode._valuesMap[code];
    if (mappedCode == null) {
      throw RealmError("Unknown SyncSessionErrorCode");
    }
.....
```

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by desistefanova**
- Add compensatingWrite error to SyncSessionErrorCode.
Fixes #1024

### CODE REVIEW

**Review by nielsenko — APPROVED** [review]

**Review by blagoev — APPROVED** [review]

**Comment by desistefanova** [comment]
> Can we write a test for this? I don't see a reason why it wouldn't work, but it would be nice to have a test that verifies it.

I added one test.

**Review by blagoev — APPROVED** [review]

File: test/subscription_test.dart [hunk 1]
```diff
@@ -605,4 +606,29 @@ Future<void> main([List<String>? args]) async {
...
+    final config = Configuration.flexibleSync(user, [Product.schema], syncErrorHandler: (syncError) {
+      compensatingWriteError = syncError;
+    });
+    final realm = getRealm(config);
+    final query = realm.query<Product>(r'stringQueryField BEGINSWITH $0', [productNamePrefix]);
+    if (realm.subscriptions.find(query) == null) {
+      realm.subscriptions.update((mutableSubscriptions) => mutableSubscriptions.add(query));
+    }
+    await realm.subscriptions.waitForSynchronization();
+    realm.write(() => realm.add(Product(ObjectId(), "doen't match subscription")));
```
Comment (nirinchev) [inline test/subscription_test.dart:624]:
```suggestion
    realm.write(() => realm.add(Product(ObjectId(), "doesn't match subscription")));
```

**Review by nirinchev — APPROVED** [review]
