### PR TITLE
realm.deleteRealm

### LINKED ISSUE #49: Implement Realm.deleteRealm
Static member of Realm that takes as an argument realm configuration and deletes all files and directories of realm. Throws RealmException if realm is not closed or if some IO exception happen. Use realm_delete_files from core API.

### PR DESCRIPTION
**Pull request by desistefanova**
Realm deleteRealm implemented - fixes #49

### CODE REVIEW

**Review by nirinchev — CHANGES_REQUESTED** [review]
This should use the Core API instead of manually deleting the files. It's not a problem when you're the only process accessing a file, but it becomes an issue with multiprocess access.

**Comment by desistefanova** [comment]
> This should use the Core API instead of manually deleting the files. It's not a problem when you're the only process accessing a file, but it becomes an issue with multiprocess access.

@nirinchev yes, we have delete_files function in the core API for .Net, but I couldn't find such method exposed in realm.h for Dart sdk. That's why we decided to implement it in Dart.

**Comment by blagoev** [comment]
Indeed we are referencing core v11.8 which does not have the delete files api. It was only recently added in https://github.com/realm/realm-core/commit/9913f7dea74465274258796933aba6b031876c38
Let me update core to newer version and we can change the implementation to use that instead of Dart APIs. I think we will support only sync delete with the core version.

**Comment by desistefanova** [comment]
> Indeed we are referencing core v11.8 which does not have the delete files api. It was only recently added in [realm/realm-core@9913f7d](https://github.com/realm/realm-core/commit/9913f7dea74465274258796933aba6b031876c38) Let me update core to newer version and we can change the implementation to use that instead of Dart APIs. I think we will support only sync delete with the core version.

It will be great. I will change it as soon as we have the new version.

**Comment by blagoev** [comment]
@desistefanova ok I merged https://github.com/realm/realm-dart/pull/170 which includes `realm_delete_files` C API

File: lib/src/realm_class.dart [hunk 1]
```diff
@@ -62,6 +63,11 @@ class Realm {
     }
   }
 
+  static void deleteRealm(Configuration config) {
```
Comment (nielsenko) [inline lib/src/realm_class.dart:66]: Should we spawn an isolate and make this async?

File: lib/src/realm_class.dart [hunk 2]
```diff
@@ -62,6 +63,11 @@ class Realm {
...
+    // TODO: To discuss: Do we need to return this bool result from realmCore?
```
Comment (nielsenko) [inline lib/src/realm_class.dart:67]: Why not? This is IO, the User needs to know if operation succeeded or not

File: lib/src/native/realm_core.dart [hunk 3]
```diff
@@ -186,6 +186,15 @@ class _RealmCore {
     return RealmHandle._(realmPtr);
   }
 
+  bool deleteRealmFiles(String path) {
+    return using((Arena arena) {
+      Pointer<Uint8> realmDeleted = arena<Uint8>();
+      _realmLib.invokeGetBool(() => _realmLib.realm_delete_files(path.toUtf8Ptr<Int8>(arena), realmDeleted), "Error deleting realm at path ${path}");
+      // TODO: To discuss: Is this the right way to check whether file is deleted according to the doc?
```
[the remark this answers is not in the document]
Comment (blagoev) [reply lib/src/native/realm_core.dart:193]: yes this is correct way to check it

[the remark this answers is not in the document]
Comment (blagoev) [reply lib/src/native/realm_core.dart:193]: I suggest we throw an exception here if the delete failed and not return a result.

File: lib/src/native/realm_core.dart [hunk 4]
```diff
@@ -186,6 +186,15 @@ class _RealmCore {
     return RealmHandle._(realmPtr);
   }
 
+  bool deleteRealmFiles(String path) {
```
Comment (blagoev) [inline lib/src/native/realm_core.dart:189]:
```suggestion
  void deleteRealmFiles(String path) {
```

File: lib/src/realm_class.dart (hunk 1 above)
Comment (blagoev) [reply lib/src/realm_class.dart:66]: I don't think we should try doing that. This should be a sync operation as all other core related.

File: lib/src/realm_class.dart (hunk 2 above)
Comment (blagoev) [reply lib/src/realm_class.dart:67]: this should throw a `RealmException` if it fails, imo

File: test/realm_test.dart [hunk 5]
```diff
@@ -1012,5 +1012,29 @@ Future<void> main([List<String>? args]) async {
       //Ensure list size is the same like teams collection size
       expect(list.length, teams.length);
     });
+
+    test('Realm deleteRealm files after closing realm', () {
```
Comment (blagoev) [inline test/realm_test.dart:1016]:
```suggestion
    test('Realm deleteRealm succeeds', () {
```

File: test/realm_test.dart [hunk 6]
```diff
@@ -1012,5 +1012,29 @@ Future<void> main([List<String>? args]) async {
...
+      var config = Configuration([Dog.schema, Person.schema]);
+      var realm = Realm(config);
+      
+      realm.close();
+      Realm.deleteRealm(config);
+
+      expect(File(config.path).existsSync(), false);
+      // TODO: For Discussion: Lock file is not deleted by core API.
```
Comment (blagoev) [inline test/realm_test.dart:1024]: this is fine as it is mentioned in the header. we should not check for it

File: test/realm_test.dart [hunk 7]
```diff
@@ -1012,5 +1012,29 @@ Future<void> main([List<String>? args]) async {
...
+      //expect(File("${config.path}.lock").existsSync(), false);
+      expect(Directory("${config.path}.management").existsSync(), false);
+    });
+
+    test('Realm deleteRealm files before closing realm expects exception', () {
```
Comment (blagoev) [inline test/realm_test.dart:1029]:
```suggestion
    test('Realm deleteRealm throws exception on an open realm', () {
```

File: test/realm_test.dart [hunk 8]
```diff
@@ -1012,5 +1012,29 @@ Future<void> main([List<String>? args]) async {
...
+      var config = Configuration([Dog.schema, Person.schema]);
+      var realm = Realm(config);
+
+      expect(() => Realm.deleteRealm(config), throws<RealmException>());
+      
+      expect(File(config.path).existsSync(), true);
+      expect(File("${config.path}.lock").existsSync(), true);
```
Comment (blagoev) [inline test/realm_test.dart:1036]: imo, we should not check for the lock file in the test.

**Review by blagoev — CHANGES_REQUESTED** [review]

File: lib/src/realm_class.dart (hunk 1 above)
Comment (blagoev) [inline lib/src/realm_class.dart:66]: As the comment on `Realm.exists` I think we should require a path here. Please check my reasoning [here ](https://github.com/realm/realm-dart/pull/171#discussion_r783772877)

**Review by blagoev — CHANGES_REQUESTED** [review]

File: lib/src/realm_class.dart (hunk 1 above)
Comment (blagoev) [reply lib/src/realm_class.dart:66]: @nielsenko @desistefanova ^

**Comment by desistefanova** [comment]
> > Indeed we are referencing core v11.8 which does not have the delete files api. It was only recently added in [realm/realm-core@9913f7d](https://github.com/realm/realm-core/commit/9913f7dea74465274258796933aba6b031876c38) Let me update core to newer version and we can change the implementation to use that instead of Dart APIs. I think we will support only sync delete with the core version.
> 
> It will be great. I will change it as soon as we have the new version.

Done.

File: lib/src/realm_class.dart (hunk 2 above)
Comment (nielsenko) [reply lib/src/realm_class.dart:67]: That is fine with me as well. As long as it cannot fail silently.

File: lib/src/native/realm_core.dart (hunk 3 above)
[the remark this answers is not in the document]
Comment (desistefanova) [reply lib/src/native/realm_core.dart:193]: Here is the description of `realm_delete_files`:
/// @param[out] did_delete_realm If non-null, set to true if the primary Realm file was deleted.
/// Discard value if the function returns an error.
/// @return true if no error occurred.

File: lib/src/realm_class.dart (hunk 1 above)
Comment (nielsenko) [reply lib/src/realm_class.dart:66]: Okay, I just don't like blocking IO on the main thread.

File: lib/src/realm_class.dart (hunk 2 above)
Comment (nirinchev) [reply lib/src/realm_class.dart:67]: It won't fail silently, but it may succeed even if an exception is called, which is why there's a return value.

Comment (nielsenko) [reply lib/src/realm_class.dart:67]: I mean on the dart side.. Or maybe I misunderstand?

File: lib/src/native/realm_core.dart (hunk 3 above)
[the remark this answers is not in the document]
Comment (nielsenko) [reply lib/src/native/realm_core.dart:193]: True, `invokeGetBool` will raise exception

[the remark this answers is not in the document]
Comment (blagoev) [reply lib/src/native/realm_core.dart:193]: yep

File: lib/src/realm_class.dart (hunk 1 above)
Comment (desistefanova) [reply lib/src/realm_class.dart]: After a discussion we decided to have only one sync method deleteReam for now.

File: lib/src/realm_class.dart (hunk 2 above)
Comment (desistefanova) [reply lib/src/realm_class.dart]: After a discussion we decided to leave the exception to be thrown by `invokeGetBool`. Return type will be void.

File: lib/src/native/realm_core.dart (hunk 3 above)
[the remark this answers is not in the document]
Comment (desistefanova) [reply lib/src/native/realm_core.dart]: Fixed in https://github.com/realm/realm-dart/pull/169/commits/0697dce4c21edbd697003715971e4e21b9d68d23

File: lib/src/realm_class.dart (hunk 1 above)
Comment (desistefanova) [reply lib/src/realm_class.dart]: Fixed in https://github.com/realm/realm-dart/pull/169/commits/0697dce4c21edbd697003715971e4e21b9d68d23

File: test/realm_test.dart (hunk 8 above)
Comment (desistefanova) [reply test/realm_test.dart]: Fixed in https://github.com/realm/realm-dart/pull/169/commits/0697dce4c21edbd697003715971e4e21b9d68d23

File: test/realm_test.dart (hunk 6 above)
Comment (desistefanova) [reply test/realm_test.dart]: Fixed in https://github.com/realm/realm-dart/pull/169/commits/0697dce4c21edbd697003715971e4e21b9d68d23

File: lib/src/native/realm_core.dart (hunk 4 above)
Comment (desistefanova) [reply lib/src/native/realm_core.dart]: Fixed in https://github.com/realm/realm-dart/pull/169/commits/0697dce4c21edbd697003715971e4e21b9d68d23

File: lib/src/native/realm_core.dart [hunk 9]
```diff
@@ -186,6 +186,13 @@ class _RealmCore {
     return RealmHandle._(realmPtr);
   }
 
+  void deleteRealmFiles(String path) {
+    return using((Arena arena) {
```
Comment (blagoev) [inline lib/src/native/realm_core.dart:190]:
```suggestion
    using((Arena arena) {
```

**Review by blagoev — COMMENTED** [review]
👍 with small change requested

**Review by nielsenko — APPROVED** [review]

**Review by blagoev — APPROVED** [review]

**Comment by desistefanova** [comment]
> This should use the Core API instead of manually deleting the files. It's not a problem when you're the only process accessing a file, but it becomes an issue with multiprocess access.

@nirinchev we've changed the implementation to use `realm_delete_files` C API. So it is done.
