### PR TITLE
Query lists arguments

### LINKED ISSUE #755: Support list comparison in RQL
As of realm-core v12.5.0 RQL supports list comparisons, but the Dart SDK does not handle list arguments. Example:

```dart
realm.query('list = $0', [[1,2,3]]);
```

### LINKED ISSUE #1084: [Bug]: Query method with IN predicate returns empty results
### What happened?

I try build query with IN predicate but return empty results.

### Repro steps

Build a List String with the values to be filtered.
Pass a List with join(",") to get concatenated values as a single string.
Build a predicate with IN using query method and pass as parameter list

### Version

realm 0.8.0+rc -> flutter  3.3.10

### What Realm SDK flavor are you using?

Local Database only

### What type of application is this?

Flutter Application

### Client OS and version

Windows 11

### Code snippets

Model:
image
Implementation:
image

Alternative (that works):
image

### Stacktrace of the exception/crash you're getting

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by desistefanova**
This PR adds support for iterable arguments  for query with `IN`-operators for `RealmResults`, `RealmList` and `RealmSet`
  ```dart
    final listOfNames = ['Ani', 'Teddy'];
    var result = realm.query<Person>(r'name IN $0', [listOfNames]);

    final setOfNames = {'Poly', 'Teddy'};
    result = realm.query<Person>(r'name IN $0', [setOfNames]);

    final iterableNames = result.map((e) => e.name);
    result = realm.query<Person>(r'name IN $0', [iterableNames]);
  ```
Added support for query on `RealmSet`.
Allow list of nullable objects when querying on `RealmList` and `RealmSet`. It was supported only for `RealmResults` before.
Fixes #755
Fixes #1084
Inspired by https://github.com/realm/realm-kotlin/pull/1389 and [realm-js tests](https://github.com/realm/realm-js/blob/4fe383de1a05b5e218cc7ca8111c2c16dda1966e/integration-tests/tests/src/tests/queries.ts#L1726)

### CODE REVIEW

**Review by nielsenko — APPROVED** [review]

File: lib/src/native/realm_core.dart [hunk 1]
```diff
@@ -2893,79 +2914,90 @@ extension _RealmLibraryEx on RealmLibrary {
...
 
 void _intoRealmQueryArg(Object? value, Pointer<realm_query_arg_t> realm_query_arg, Allocator allocator) {
-  realm_query_arg.ref.arg = allocator<realm_value_t>();
-  realm_query_arg.ref.nb_args = 1;
-  realm_query_arg.ref.is_list = false;
-  _intoRealmValue(value, realm_query_arg.ref.arg, allocator);
+  if (value is Iterable) {
+    realm_query_arg.ref.nb_args = value.length;
+    realm_query_arg.ref.is_list = true;
+    realm_query_arg.ref.arg = allocator.call<realm_value>(value.length);
```
Comment (blagoev) [inline lib/src/native/realm_core.dart:2928]:
```suggestion
    realm_query_arg.ref.arg = allocator<realm_value>(value.length);
```

**Review by blagoev — APPROVED** [review]
